#
# Copyright 2021 Basislager Services
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

name: Book
on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  book:
    name: 'Generate book and push results'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: 'Install dependencies'
        run: |
          sudo apt-get install -y \
            chromium-browser \
            chromium-chromedriver \
            curl \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-latex-recommended
          curl -L -o /tmp/pandoc.deb 'https://github.com/jgm/pandoc/releases/download/2.16.2/pandoc-2.16.2-1-amd64.deb'
          sudo dpkg -i /tmp/pandoc.deb

      - name: 'Configure Git'
        run: |
          git config --global user.name 'Basislager Services'
          git config --global user.email 'services@basislager.fun'
          git config --global url.'https://${{secrets.REPO_TOKEN}}:@github.com/'.insteadOf 'https://github.com/'

      - name: 'Install package'
        run: pip install .

      - name: 'Run book generator for Unsin(n)kable III'
        run: |
          tickergadse-book \
            --git-repo 'https://github.com/basislagerservices/data.git' \
            --book logbook \
            --output books/unsinnkable.pdf \
            --output books/unsinnkable.epub

      - name: 'Run book generator for Raumschiff Ersterpreis'
        run: |
          tickergadse-book \
            --git-repo 'https://github.com/basislagerservices/data.git' \
            --book ersterpreis \
            --output books/ersterpreis.pdf \
            --output books/ersterpreis.epub
